apiVersion: apps/v1
kind: Deployment
metadata:
  name: upstream
  labels:
    app: upstream
spec:
  selector:
    matchLabels:
      app: upstream
  template:
    metadata:
      labels:
        app: upstream
    spec:
      containers:
        - name: upstream
          image: containous/whoami:latest

---
apiVersion: v1
kind: Service
metadata:
  name: upstream
spec:
  selector:
    app: upstream
  ports:
    - name: upstream
      protocol: TCP
      port: 80
